version: "3"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5001:5001"
    networks: 
      - internal
    depends_on:
      - redis
  worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks: 
      - internal
  redis:
    image: redis
    networks: 
      - internal

networks:
  internal:
